/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.seong.pms;

import com.seong.pms.handler2.ListMenuHandler;
import com.seong.pms.handler2.WriteMenuHandler;
import com.seong.util.Prompt;

public class App2 {

  public static boolean company = true;

  public static void main(String[] args) {
    //    MemberHandler memberHandler = new MemberHandler();

    WriteMenuHandler writeHandler = new WriteMenuHandler();
    ListMenuHandler listHandler = new ListMenuHandler(writeHandler.memberHandler, writeHandler.paperHandler);
    //    UpdateHandler updateHandler = new UpdateHandler(writeHandler.memberHandler);


    while (company)
    {
      String menu = Prompt.inputString("[문서관리 시스템]\n1. 서류작성\n2. 서류목록\n3. 서류수정\n99. 종료\n> ");

      if (menu.equals("1"))
      {
        // 서류작성메뉴
        writeHandler.writeMenu();
      } else if (menu.equals("2")) 
      {
        // 서류목록
        if (writeHandler.paperHandler.holidayList.exist())
        {
          Prompt.println("작성된 문서가 없습니다.");
          Prompt.println("");
          continue;
        }

        //        System.out.println("준비중입니다.");
        //        continue;
        listHandler.paperMenu();

      } else if (menu.equals("3"))
      {
        //        if (MemberHandler.members[0] == null)
        //        {
        //          Prompt.println("수정할 서류가 없습니다.");
        //          Prompt.println("");
        //          continue;
        //        }

        System.out.println("준비중입니다.");
        continue;
        //        updateHandler.service();

      } else if (menu.equals("99"))
      {
        // 종료
        Prompt.println("시스템을 종료합니다.");
        break;
      } else if (Prompt.inputCheck(menu))
      {
        Prompt.println("입력형식이 맞지 않습니다. 숫자만 입력해 주세요.");
      } else
      {
        Prompt.println("없는 메뉴 입니다. 다시 입력해주세요.");
      } // if

      Prompt.println("");
    } // while



    Prompt.close();
  } // main
}


// 인스턴스으 ㅣ필드 값을 ㅂ이트 배열로 변환하 출력하는 것이다.
// 클래스 정보 및 필드의 타입 정보, 클래스 버전도 포함한다.

// 직렬화를 통해 저장된 바이트 배영ㄹ을 읽어서 자바 객체로 변환하는 것이다.
// 